# export HOST_IP=`ipconfig getifaddr en0`
version: '3'
services:
  cassandra:
    image: "cassandra:latest"
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"

  api-writer:
    image: "iot-assignment-api-writer"
    ports:
      - "8080:8080"
      - "2540:2551"
    environment:
      - AKKA_HOST=${HOST_IP}
      - AKKA_PORT=2540

  api-stats:
    image: "iot-assignment-api-stats"
    ports:
      - "8081:8080"
      - "2520:2551"
    environment:
      - AKKA_HOST=${HOST_IP}
      - AKKA_PORT=2520

  storer_1:
    image: "iot-assignment-storer"
    ports:
      - "2550:2551"
    environment:
      - AKKA_HOST=${HOST_IP}
      - AKKA_PORT=2550

  storer_2:
    image: "iot-assignment-storer"
    ports:
      - "2551:2551"
    environment:
      - AKKA_HOST=${HOST_IP}

  reader_1:
      image: "iot-assignment-reader"
      ports:
        - "2531:2551"
      environment:
        - AKKA_HOST=${HOST_IP}
        - AKKA_PORT=2531

  reader_2:
      image: "iot-assignment-reader"
      ports:
        - "2532:2551"
      environment:
        - AKKA_HOST=${HOST_IP}
        - AKKA_PORT=2532
